# Generated by Django 2.2.4 on 2019-11-20 16:31

from django.db import migrations


def get_status_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(construction_year__gte=2015):
        Flat.objects.update_or_create(town=flat.town,address=flat.address,price=flat.price,defaults={'new_building':True})

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20191117_1849'),
    ]

    operations = [
        migrations.RunPython(get_status_building)
    ]
