# Generated by Django 2.2.4 on 2019-12-07 07:30

from django.db import migrations


def create_relations(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner=owner.owner))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20191130_2111'),
    ]

    operations = [
        migrations.RunPython(create_relations)
    ]
